# Generated by Django 6.0 on 2026-02-16 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralServiceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('A1 MK', 'A1 MK'), ('MT', 'Makedonski Telekom')], max_length=50)),
                ('district', models.CharField(max_length=255)),
                ('service_sign', models.CharField(max_length=100, verbose_name='Service ID')),
                ('service_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('speed', models.CharField(max_length=100)),
                ('contract_start_date', models.DateField()),
                ('access_address', models.CharField(max_length=255)),
                ('service_origin', models.CharField(blank=True, choices=[('ILL', 'ILL'), ('MEP', 'MEP')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MPLSPoP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pop_hostname', models.CharField(max_length=255)),
                ('vsi', models.CharField(max_length=255)),
                ('vsi_id', models.CharField(max_length=255)),
                ('vsi_peers', models.TextField()),
                ('l3_interface', models.CharField(max_length=255)),
                ('vpn_instance', models.CharField(max_length=255)),
                ('transport_ip_address', models.GenericIPAddressField()),
                ('routed_lan_pool', models.CharField(max_length=255)),
                ('service_port', models.CharField(max_length=255)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('interface_type', models.CharField(max_length=255)),
                ('service_vlan', models.PositiveIntegerField()),
                ('rate_limit', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('general_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpls_pops', to='services.generalserviceinfo')),
            ],
            options={
                'verbose_name': 'MPLS PoP',
                'verbose_name_plural': 'MPLS PoPs',
            },
        ),
    ]
