# Generated by Django 6.0 on 2026-02-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalserviceinfo',
            name='operator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
