# Generated by Django 6.0 on 2026-02-23 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_generalserviceinfo_operator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralServiceInfo',
            new_name='GeneralCCInfo',
        ),
        migrations.CreateModel(
            name='ServerRoomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srv1_field_value', models.CharField(blank=True, max_length=255, null=True)),
                ('srv1_room', models.CharField(blank=True, max_length=255, null=True)),
                ('srv1_rack', models.CharField(blank=True, max_length=255, null=True)),
                ('srv1_odf', models.CharField(blank=True, max_length=255, null=True)),
                ('srv1_position', models.CharField(blank=True, max_length=255, null=True)),
                ('srv1_cust_eq_info', models.CharField(blank=True, max_length=255, null=True)),
                ('srv1_cust_int_info', models.CharField(blank=True, max_length=255, null=True)),
                ('srv2_field_value', models.CharField(blank=True, max_length=255, null=True)),
                ('srv2_room', models.CharField(blank=True, max_length=255, null=True)),
                ('srv2_rack', models.CharField(blank=True, max_length=255, null=True)),
                ('srv2_odf', models.CharField(blank=True, max_length=255, null=True)),
                ('srv2_position', models.CharField(blank=True, max_length=255, null=True)),
                ('srv2_cust_eq_info', models.CharField(blank=True, max_length=255, null=True)),
                ('srv2_cust_int_info', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('general_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_details', to='services.generalccinfo')),
            ],
            options={
                'verbose_name': 'Server Room Details',
                'verbose_name_plural': 'Server Room Details',
            },
        ),
        migrations.DeleteModel(
            name='MPLSPoP',
        ),
    ]
