# Generated by Django 5.2.9 on 2025-12-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("service_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("sk", "Skopje"),
                            ("oh", "Ohrid"),
                            ("su", "Struga"),
                            ("bt", "Bitola"),
                            ("st", "Strumica"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        choices=[("cisco", "Cisco"), ("huawei", "Huawei")],
                        max_length=20,
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[("m1", "Model 1"), ("m2", "Model 2")], max_length=20
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
