# Generated by Django 5.2.9 on 2025-12-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deployment",
            name="manufacturer",
            field=models.CharField(
                choices=[
                    ("", "Select Manufacturer"),
                    ("cisco", "Cisco"),
                    ("huawei", "Huawei"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="deployment",
            name="model_type",
            field=models.CharField(
                choices=[("", "Select Option"), ("m1", "Model 1"), ("m2", "Model 2")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="deployment",
            name="region",
            field=models.CharField(
                choices=[
                    ("", "Select Region"),
                    ("sk", "Skopje"),
                    ("oh", "Ohrid"),
                    ("su", "Struga"),
                    ("bt", "Bitola"),
                    ("st", "Strumica"),
                ],
                max_length=10,
            ),
        ),
    ]
