# Generated by Django 5.2.9 on 2025-12-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_deployment_manufacturer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("service_id", models.CharField(blank=True, max_length=255, null=True)),
                ("region", models.CharField(max_length=50)),
                ("manufacturer", models.CharField(max_length=50)),
                ("model_type", models.CharField(max_length=50)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="deployment",
            name="model_type",
            field=models.CharField(
                choices=[("", "Select Model"), ("m1", "Model 1"), ("m2", "Model 2")],
                max_length=20,
            ),
        ),
    ]
