# Generated by Django 6.0 on 2025-12-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_task_alter_deployment_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='region',
            field=models.CharField(choices=[('', 'Select Region'), ('sk', 'Skopje'), ('oh', 'Ohrid'), ('su', 'Struga'), ('bt', 'Bitola'), ('st', 'Strumica'), ('be', 'Berovo'), ('ko', 'Kochani'), ('ge', 'Gevgelija'), ('st_sh', 'Shtip'), ('pe', 'Pehchevo'), ('vi', 'Vinica'), ('va', 'Valandovo'), ('do', 'Dojran')], max_length=10),
        ),
    ]
