# Generated by Django 6.0 on 2025-12-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_deployment_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='reserved_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
