# Generated by Django 6.0 on 2025-12-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_deployment_reserved_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reserved_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='service_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='region',
            field=models.CharField(choices=[('', 'Select Region'), ('sk', 'Skopje'), ('oh', 'Ohrid'), ('su', 'Struga'), ('bt', 'Bitola'), ('st', 'Strumica'), ('be', 'Berovo'), ('ko', 'Kochani'), ('ge', 'Gevgelija'), ('st_sh', 'Shtip'), ('pe', 'Pehchevo'), ('vi', 'Vinica'), ('va', 'Valandovo'), ('do', 'Dojran')], max_length=50),
        ),
    ]
